name: Test DigitalOcean VM deploy and destroy

on:
  workflow_dispatch:

jobs:
  do_vm_terraform_deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ensure netcat is installed
        run: sudo apt-get update && sudo apt-get install -y netcat-openbsd
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"
      - name: Initialize Terraform
        run: terraform init
        working-directory: tests/digitalocean/infra-only
      - name: Run Terraform apply
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: terraform apply --auto-approve -var "do_token=$DIGITALOCEAN_TOKEN"
        working-directory: tests/digitalocean/infra-only
      - name: Get public IP from Terraform output
        id: ip
        run: |
          ip=$(terraform output -raw first_instance_public_ip)
          echo "INSTANCE_IP=$ip" >> $GITHUB_ENV
        working-directory: tests/digitalocean/infra-only
      - name: Wait for SSH (port 22) to become available
        run: |
          echo "Waiting for port 22 on $INSTANCE_IP..."
          for i in {1..30}; do
            if nc -zv $INSTANCE_IP 22; then
              echo "Port 22 is open."
              exit 0
            fi
            echo "Attempt $i failed, retrying in 10s..."
            sleep 10
          done
          echo "SSH not available after 30 attempts. Failing."
          exit 1
        env:
          INSTANCE_IP: ${{ env.INSTANCE_IP }}
      - name: Run Terraform Destroy
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: terraform destroy --auto-approve -var "do_token=$DIGITALOCEAN_TOKEN"
        working-directory: tests/digitalocean/infra-only
